spring:
  datasource:
    url: jdbc:mysql://localhost:3306/modazin
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # 콘솔에 SQL 쿼리를 출력할지 여부를 결정
    properties:
      hibernate:
        format_sql: true # SQL 쿼리를 보기 좋게 포맷팅
        dialect: org.hibernate.dialect.MySQL8Dialect